# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zy/Desktop/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zy/Desktop/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zy/Desktop/test/CMakeFiles /home/zy/Desktop/test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zy/Desktop/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xml_test

# Build rule for target.
xml_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xml_test
.PHONY : xml_test

# fast build rule for target.
xml_test/fast:
	$(MAKE) -f CMakeFiles/xml_test.dir/build.make CMakeFiles/xml_test.dir/build
.PHONY : xml_test/fast

src/tinyxml2.o: src/tinyxml2.cpp.o

.PHONY : src/tinyxml2.o

# target to build an object file
src/tinyxml2.cpp.o:
	$(MAKE) -f CMakeFiles/xml_test.dir/build.make CMakeFiles/xml_test.dir/src/tinyxml2.cpp.o
.PHONY : src/tinyxml2.cpp.o

src/tinyxml2.i: src/tinyxml2.cpp.i

.PHONY : src/tinyxml2.i

# target to preprocess a source file
src/tinyxml2.cpp.i:
	$(MAKE) -f CMakeFiles/xml_test.dir/build.make CMakeFiles/xml_test.dir/src/tinyxml2.cpp.i
.PHONY : src/tinyxml2.cpp.i

src/tinyxml2.s: src/tinyxml2.cpp.s

.PHONY : src/tinyxml2.s

# target to generate assembly for a file
src/tinyxml2.cpp.s:
	$(MAKE) -f CMakeFiles/xml_test.dir/build.make CMakeFiles/xml_test.dir/src/tinyxml2.cpp.s
.PHONY : src/tinyxml2.cpp.s

src/xml2_test.o: src/xml2_test.cpp.o

.PHONY : src/xml2_test.o

# target to build an object file
src/xml2_test.cpp.o:
	$(MAKE) -f CMakeFiles/xml_test.dir/build.make CMakeFiles/xml_test.dir/src/xml2_test.cpp.o
.PHONY : src/xml2_test.cpp.o

src/xml2_test.i: src/xml2_test.cpp.i

.PHONY : src/xml2_test.i

# target to preprocess a source file
src/xml2_test.cpp.i:
	$(MAKE) -f CMakeFiles/xml_test.dir/build.make CMakeFiles/xml_test.dir/src/xml2_test.cpp.i
.PHONY : src/xml2_test.cpp.i

src/xml2_test.s: src/xml2_test.cpp.s

.PHONY : src/xml2_test.s

# target to generate assembly for a file
src/xml2_test.cpp.s:
	$(MAKE) -f CMakeFiles/xml_test.dir/build.make CMakeFiles/xml_test.dir/src/xml2_test.cpp.s
.PHONY : src/xml2_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... xml_test"
	@echo "... src/tinyxml2.o"
	@echo "... src/tinyxml2.i"
	@echo "... src/tinyxml2.s"
	@echo "... src/xml2_test.o"
	@echo "... src/xml2_test.i"
	@echo "... src/xml2_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

